application: WebOSpro
version: alpha-001
runtime: php55
api_version: 1
 
manipuladores:

- url: /
  guión: index.php
  
- url: /style
  static_dir: stylesheets
  
- url: /imag
  static_dir: static/images
  
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$